### ISSUE TITLE
Add Definition of Done

### ISSUE THREAD

**Issue by montymxb** [cs361fall2018/project-team40#10]
We need to add a Definition of Done to our wiki. This can be closed once that's been addressed.

**Comment by montymxb** [comment]
@cs361fall2018/team40 I updated the [Definition of Done Page](https://github.com/cs361fall2018/project-team40/wiki/Definition-of-Done). Let me know what you guys think. If there's nothing else to change/add/remove we can close this out.

**Comment by horinezachary** [comment]
Looks good to me!

**Comment by fireball1983** [comment]
I think this is good since we seem to follow it pretty closely. I'm gonna close out this issue.
