### ISSUE TITLE
Create Submarine Subclass

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#107]
![image](https://user-images.githubusercontent.com/6768190/48384180-fe917680-e69d-11e8-8cc2-57c2a2570d56.png)

**Comment by montymxb** [comment]
@fireball1983 just saw that you're assigned here. Is this the same as #110 ?

**Comment by montymxb** [comment]
Actively working on a PR for this. I have basic placing logic down, just need to setup the attack components properly. In particular this is what I need to tackle still.
- Add test to prove attacking the same square twice doesn't drop health on a submarine
- Add test to prove attacking with a regular weapon hurts a non-submerged submarine
- Add test to prove attacking with a regular cannot hurt a submerged submarine
- Add test to prove attacking with a laser hurts a sub that is submerged or not
- Add test to prove a sub can be placed under a ship if it's submerged
- Add test to prove a sub cannot be placed under a ship if not submerged
- Add test to prove a bomb will only damage a surface ship and not the sub underneath
- Add test to prove a laser will damage all ships on a square, including an underlying sub
- Add UI option to toggle submerging/surfacing a sub when placing it
Shouldn't be too long to finish the rest of this though.

**Comment by montymxb** [comment]
Closed by #122
