### ISSUE TITLE
Implement Ship Movement

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#114]
![image](https://user-images.githubusercontent.com/6768190/48384386-fede4180-e69e-11e8-9028-05647732d80d.png)
This consumes the player's turn.
![image](https://user-images.githubusercontent.com/6768190/48455699-0b32cf00-e771-11e8-8cce-e72c8c3e04bb.png)

**Comment by montymxb** [comment]
Closed with #128
