### ISSUE TITLE
Placing Sets at Unexpected Position

### ISSUE THREAD

**Issue by montymxb** [cs361fall2018/project-team40#17]
Placing the first ship works on the GUI now, but it places at an incorrect position and orientation relative to where you click. Additionally once the first ship has been placed subsequent placements are not possible.

**Comment by horinezachary** [comment]
I will work through this in a bit

**Comment by horinezachary** [comment]
The issue is that the random ship is being drawn on the lower board rather than the player's ship. the back-end is receiving and placing the ships correctly, they just don't show up where they are supposed to.

**Comment by montymxb** [comment]
Alright. I'll take a look and see if I can pin that issue down.

**Comment by horinezachary** [comment]
Feel free to take a look, I was having difficulty finding this. I won't be able to look at it for at least 2 hours. There were some slack posts that asked about this issue that you might take a look at
