### ISSUE TITLE
Complete "Board" Constructor

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#2]
This looks like an array, I think we come up with the dimensions.

**Comment by fireball1983** [comment]
Maybe we can have "1" symbolize a missle, "2-4" for the ship type, then empty or 0 for the empty spots within the array

**Comment by fireball1983** [comment]
Forget the last one for now, I think the board is an arraylist of squares, I'm going to keep checking

**Comment by montymxb** [comment]
@fireball1983 If you want to go for this one let me know, otherwise I can grab it too along with #1.

**Comment by fireball1983** [comment]
@montymxb I'll be back at around 8, I'm not sure how long it'd take to make but if you can smash it out quickly then go for it.

**Comment by montymxb** [comment]
Closed by merging #13
