### ISSUE TITLE
Bad logic in Board.placeShip

### ISSUE THREAD

**Issue by montymxb** [cs361fall2018/project-team40#20]
@horinezachary there's a logic issue in [Board.placeShip on line 41](https://github.com/cs361fall2018/project-team40/blob/master/src/main/java/cs361/battleships/models/Board.java#L41).

I've included a snippet of the stack trace to help pin it down for you. It's just an array out of bounds exception that intermittently shows up, due to the random placement of the bot ships.
```
java.lang.ArrayIndexOutOfBoundsException: -1

	at cs361.battleships.models.Board.placeShip(Board.java:41)
	at cs361.battleships.models.Game.placeShip(Game.java:30)
	at cs361.battleships.models.GameTest.testGoodplaceship(GameTest.java:30)
	....
```

**Comment by horinezachary** [comment]
I believe the issue is that the random values are created from zero, not from 1 like the user ones

**Comment by horinezachary** [comment]
I can fix this after 4pm.
