### ISSUE TITLE
Add Target platform and user description to Wiki

### ISSUE THREAD

**Issue by horinezachary** [cs361fall2018/project-team40#40]
We will need to decide what target platform we are designing for, and describe our target user

**Comment by fireball1983** [comment]
I believe we decided that it was for pc monitors (16x9) and was for the user that wanted the classic battleship experience. Probably means that it's aesthetically designed like the game itself.

**Comment by montymxb** [comment]
I actually just put this one in @fireball1983 . But give it a look over and refine it as needed. When it's good we can close this out.

**Comment by fireball1983** [comment]
I think it's good.
