### ISSUE TITLE
Create application designs

### ISSUE THREAD

**Issue by horinezachary** [cs361fall2018/project-team40#41]
Everybody will need to come up with and draw out 3 different designs for how our user interface will be laid out and how it will look. We will then choose the best three, and then merge them into the best design.

**Comment by montymxb** [comment]
@cs361fall2018/team40 I've finished up my prototypes, and michael has finished up his. Just need Jhonathan's and Zach's uploaded before we can start making decisions.

**Comment by fireball1983** [comment]
This one is finished.
