### ISSUE TITLE
Add delay to AI attacks

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#48]
Small delay, 1/3 of a second?

**Comment by fireball1983** [comment]
Adding a timeunit or thread.sleep causes both user/opponent inputs to come at the same time after the delay.

**Comment by montymxb** [comment]
Yeah, about 1/3 or 1/2 would be good, with some sort of visual cue perhaps.

**Comment by fireball1983** [comment]
I'm going to add the 1/2 thread delay then. As for the visual cue, we can leave that to either attack history or the user feedback section.

**Comment by montymxb** [comment]
Digging into the code a bit we might want to let this one go for now. Everytime a move is made the who screen is redrawn. When that happens it's not for either the player or AI, just everything all over again (not terribly efficient either). We could setup this delay, but it would have to involve a good amount of additions for a small feature.
