### ISSUE TITLE
Add some sort of feedback to a player attack

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#49]
This is an extra issue, but there should probably be some sort of feedback when the user does something.

**Comment by montymxb** [comment]
If you can think of something specific write a user story for it.

**Comment by montymxb** [comment]
A little CSS animation and an added entry to the battle report should satisfy this.

**Comment by montymxb** [comment]
Closing as the battle report is the feedback, and just needs to be adjusted to account for sink I think.
