### ISSUE TITLE
Clicking vertical causes shadowed placement

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#50]
![xqsduyq](https://user-images.githubusercontent.com/6768190/47477703-7b39df00-d7db-11e8-957f-4306eebe2498.png)

Upon clicking vertical (tab then spacebar), the boxes not including the first one will be autoplaced. These disappear upon placing a ship.

I need to clarify, this means that the last 3 boxes (aqua) will auto place.

**Comment by montymxb** [comment]
@fireball1983 You can probably add an additional `:hover` selector, but for placed. It looks like `td:hover` is overriding the following aqua because it pertains to a specific state. Adding an additional `.placed:hover{ background-color: aqua }` after should fix it.

**Comment by fireball1983** [comment]
Added more clarity to the issue. I'll try that fix when I can.

**Comment by montymxb** [comment]
@fireball1983 I'll make a quick fix for it and push the change into your PR.

**Comment by montymxb** [comment]
Fixed by #51
