### ISSUE TITLE
Get the "result" class explained

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#7]
I'm curious about the function of each function in result because it looks like it gets a lot of its functions from the other classes.

**Comment by montymxb** [comment]
Looks like it should hold some extra properties:
- result (AttackStatus object indicating what the result of the attack was)
- ship (if a ship was hit)
- location (square object that was attacked)

The only thing being used right now is the result, but we'll probably use the others as we go along. The result object looks like it's going to be populated in the [attack method of Board](https://github.com/cs361fall2018/project-team40/blob/master/src/main/java/cs361/battleships/models/Board.java#L26...L29), giving us a spot to start.

**Comment by johnnybecerra** [comment]
By result, you mean whether it missed or hit?

**Comment by montymxb** [comment]
@johnnybecerra we're talking about the [Result class in Result.java](https://github.com/cs361fall2018/project-team40/blob/master/src/main/java/cs361/battleships/models/Result.java). It's a bundle object of sorts, holding arbitrary data that results from an attack. It's not there yet, but it will have an [AttackStatus enum](https://github.com/cs361fall2018/project-team40/blob/master/src/main/java/cs361/battleships/models/AtackStatus.java) which correspond to the values for hit, miss, etc.

**Comment by montymxb** [comment]
I'm going to close this out since it's more a question, and John is working on the implementation for this.
