### ISSUE TITLE
Refactor Code with SOLID principles

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#81]
Search for code smells and whatnot. Creates subclasses etc

**Comment by fireball1983** [comment]
![capture](https://user-images.githubusercontent.com/6768190/48109655-37909d80-e1fd-11e8-82a1-94134b55451a.PNG)

**Comment by fireball1983** [comment]
![capture](https://user-images.githubusercontent.com/6768190/48109711-5ee76a80-e1fd-11e8-99ac-5b18e1d654f1.PNG)

**Comment by montymxb** [comment]
Closed with #104
