### ISSUE TITLE
Captain's Quarters super mega rules (read this my dudes)

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#83]
As we discussed on Tuesday, we said that we would consider just overloading a method in the ship superclass. Consider creating a class, though it's up to you guys.

Only the Destroyers and Battleships have a captain's quarters have armor, meaning they take two shots.
The minesweeper captain's quarter only takes **1 shot.**

- A captain's quarters has 2 health, the first hit will miss, then next will hit. Essentially
Player hits captain's quarters
- Attack.status.MISS is returned (or hit if we have 2 health)

With our current design, it cannot be attacked twice as we have it so that attacks can only occur once.

Player hits captain's quarters again
- Attack.status. HIT is returned. 
Ship is sunk

The positions are as follows. 
![image](https://user-images.githubusercontent.com/6768190/48115355-76cbe800-e217-11e8-9ddc-3e202135c913.png)
As you can notice, it's always the 2nd to last square, or in fancier terms, size-1.

There is no requirement for a separate UI for a captain's quarters with 1 hit. It is up to you.

**Comment by fireball1983** [comment]
To say again, creating a captain's quarter subclass, then just having place ship check when the index is == to size-1 and then place that square seems easier.

**Comment by montymxb** [comment]
Closing this since captain's quarters logic is in place
