### ISSUE TITLE
Create sonar pulse button UI

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#85]
Create the UI, so the javascript and CSS
This one can be fairly detailed, so things like:
- Different visuals if you can use it or not
- The amount you have left, max being 2

A check list might be good, it's up to implementation as this is not a requirement.

**Comment by johnnybecerra** [comment]
The changing visuals will have to be implemented after actually getting the sweep to work

**Comment by montymxb** [comment]
Closed with #94 merged
