### ISSUE TITLE
Implement Sonar Pulse

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#87]
Pulse can only be used
- After the first enemy ship is sunk
- Only can be used twice
- Does not reveal the captain's quarters.
- It doesn't follow bound rules, parts of the sonar pulse can be out of bounds.
- 
![image](https://user-images.githubusercontent.com/6768190/48120751-e1851f80-e227-11e8-9a41-38b98f10e9de.png)
13 squares in total

**Comment by fireball1983** [comment]
I'll try this one.

**Comment by montymxb** [comment]
Changed the name, since Jhonathan is working on the graphics component I'll also hook in the actual logic for this client side as well (JS) in addition to the server side (Java).

**Comment by montymxb** [comment]
Done with #100
