### ISSUE TITLE
Create Captain's Quarters Class

### ISSUE THREAD

**Issue by fireball1983** [cs361fall2018/project-team40#93]
Seems easier this way. The position is uniform.

**Comment by fireball1983** [comment]
Not sure if this works or not right now, the issue is that you can only place 1 ship. On the bright side, the tests pass.

**Comment by montymxb** [comment]
@fireball1983 fixed up the branch you were working on so the captain's detection and setup works now. I stripped out the Captain's quarters class as it didn't contain any unique properties, was just setting the 'captain' attribute of the Square class. A one liner in board achieved the same effect.

Also the issue you were having with it not running is that ninja attempts to determine what it should setup into and out of a class by reading it's getters & setters. This mean that if you had a function called setCaptain or getCaptain it would just create a key/value pair called "captain" in json. This was causing all sorts of unexpected issues, but it's good to know that's how it determines how to build the underlying JSON.

**Comment by fireball1983** [comment]
As Ben noted, it was easier to simply add a field to the square class with the accompanying getters and setters.
