### ISSUE TITLE
Hits not displaying correctly

### ISSUE THREAD

**Issue by johnnybecerra** [cs361fall2018/project-team40#98]
For the ships with 3+ squares, the first hit is detected and displayed correctly, but further hits are displayed with white pegs until the captain's quarters are hit a second time, at which point the ship is marked as sunk.

**Comment by montymxb** [comment]
Is this still a bug? I didn't see anything like this pop up when I was working on things, just double checking.

**Comment by fireball1983** [comment]
![image](https://user-images.githubusercontent.com/6768190/48245524-13b98d00-e3a0-11e8-91c4-0dc1100df103.png)
![image](https://user-images.githubusercontent.com/6768190/48245533-1b793180-e3a0-11e8-850c-6119f6874bf1.png)

This is the current state, from what I remember, it isn't a requirement to have different colors.
